export const TEXT_CONTENT = {
  btnHome: 'Reset Search',
  btnSearch: 'Search',
  btnErrorHome: 'Home',
  itemYearStub: 'No information',
  itemRaitingStub: 'Unranked',
  errorTitle: 'Oops',
  errorText: 'Something went wrong...',
  errorPageTitle: '404',
  errorPageText: 'Not found...',
  errorID: '9ce1093a-82d7-4c43-b702-925b4e40e0b6',
  loaderText: 'Loading...',
  searchPH: 'Type here to search...',
  barUnselectBtn: 'Unselect all',
  barDownloadBtn: 'Download',
  metaTitle: 'Kinomania',
  metaDescr: 'Here you can find information about favorite movies and tv series',
}
